services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro

  tailwind:
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -lc "npm install && npm run dev"
    stdin_open: true
    tty: true
